name: orbit-dataset-release
channels:
  - pytorch
  - plotly
dependencies:
  - python=3.7
  - pip=20.0.2=py37_3
  - plotly=4.8.1=py_0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - tqdm=4.62.3
  - pip:
    - thop==0.1.1.post2207130030
    - timm==0.6.7
